version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript/"
    schedule:
      interval: "monthly"
    groups:
      # Group all minor and patch updates in a single PR
      js-minor:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "MAINT"
    labels: []
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
