changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Breaking changes
      labels:
        - BREAKING
    - title: Added
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - ci
    - title: Other Changes
      labels:
        - "*"
