name: Bug Report
description: Report incorrect behavior in the shap library
title: "BUG: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: Please describe the issue.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide a minimal, self-contained example that reproduces the issue.
      placeholder: |
        import shap

        ...
      render: python
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Note**: without a working Minimal Reproducible Example, the maintainers will not be able to help you and your issue will be closed!

        Your example should be:

        1. **Minimal**: Use as little code as possible that still produces the same problem.
        2. **Self-contained**: Provide all minimal imports, data and code needed to reproduce the problem.
        3. **Verifiable**: Test the example to make sure it reproduces the problem.

        See [Matt's guide](https://matthewrocklin.com/minimal-bug-reports) for further information on how to write helpful bug reports.
  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: Copy & paste the traceback of the error (if relevant).
      placeholder: |
        Traceback (most recent call last):
          File "/shap/__init__.py", line 4, in <module>
            import foo
        NameError: name 'foo' is not defined
      render: shell
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe or show a code example of the expected behavior.
  - type: checkboxes
    id: checks
    attributes:
      label: Bug report checklist
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
          required: true
        - label: I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
        - label: I'd be interested in making a PR to fix this bug
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: What version of the shap library are you using?
    validations:
      required: true
