# Type stub for shap/__init__.py
# This file defines all the imports that are lazily loaded via lazy_loader

# Version
__version__: str

# Core components from _explanation
from . import actions as actions

# Submodules
from . import datasets as datasets

# Explainers module and individual explainers
from . import explainers as explainers
from . import links as links
from . import maskers as maskers
from . import models as models
from . import cext as cext

# Plots module and functions (may be UnsupportedModule if matplotlib not available)
from . import plots as plots
from . import utils as utils
from ._explanation import Cohorts as Cohorts
from ._explanation import Explanation as Explanation

# From actions
from .actions import ActionOptimizer as ActionOptimizer
from .explainers import AdditiveExplainer as AdditiveExplainer
from .explainers import CoalitionExplainer as CoalitionExplainer
from .explainers import DeepExplainer as DeepExplainer
from .explainers import ExactExplainer as ExactExplainer
from .explainers import Explainer as Explainer
from .explainers import GPUTreeExplainer as GPUTreeExplainer
from .explainers import GradientExplainer as GradientExplainer
from .explainers import KernelExplainer as KernelExplainer
from .explainers import LinearExplainer as LinearExplainer
from .explainers import PartitionExplainer as PartitionExplainer
from .explainers import PermutationExplainer as PermutationExplainer
from .explainers import SamplingExplainer as SamplingExplainer
from .explainers import TreeExplainer as TreeExplainer
from .explainers import other as other

# Plot functions (available through __getattr__ lazy loading)
from .plots._bar import bar_legacy as bar_legacy
from .plots._beeswarm import summary_legacy as summary_legacy
from .plots._beeswarm import summary_legacy as summary_plot
from .plots._decision import decision as decision
from .plots._decision import multioutput_decision as multioutput_decision
from .plots._embedding import embedding as embedding
from .plots._force import force as force
from .plots._force import getjs as getjs
from .plots._force import initjs as initjs
from .plots._force import save_html as save_html
from .plots._group_difference import group_difference as group_difference
from .plots._heatmap import heatmap as heatmap
from .plots._image import image as image
from .plots._monitoring import monitoring as monitoring
from .plots._partial_dependence import partial_dependence as partial_dependence
from .plots._scatter import dependence_legacy as dependence_legacy
from .plots._text import text as text
from .plots._violin import violin as violin
from .plots._waterfall import waterfall as waterfall

# From utils
from .utils import approximate_interactions as approximate_interactions
from .utils import sample as sample
from .utils._legacy import kmeans as kmeans

# Note: Some plot functions may be replaced with unsupported() if matplotlib is not available
# In that case, they would have type: Callable[..., Any] that raises ImportError

# Module-level variables
have_matplotlib: bool
_no_matplotlib_warning: str

# __all__ is dynamically generated by lazy_loader
__all__: list[str]
