# Ensure that the javascript package can be built with webpack
# Runs on any PRs that modify the javascript directory
# Also runs Python tests if the bundle.js is updated

name: test_js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "javascript/**"

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: lts/Hydrogen
    - run: npm ci
      working-directory: ./javascript
    - run: npm run build
      working-directory: ./javascript
    - run: npm run test
      working-directory: ./javascript
    # Copy the bundle to the Python package location
    - run: cp build/bundle.js ../shap/plots/resources/bundle.js
      working-directory: ./javascript
